config = {'train_data_path':['/content/drive/My Drive/zip/subset9/',
                             '/content/drive/My Drive/zip/subset1/',
                             '/content/drive/My Drive/zip/subset2/',
                             '/content/drive/My Drive/zip/subset3/'],
          'val_data_path':['/content/drive/My Drive/zip/subset0/'], 
          'test_data_path':['/content/drive/My Drive/zip/subset0/'], 
          
          'train_preprocess_result_path':'/content/drive/My Drive/zip/result/subset9/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'/content/drive/My Drive/zip/result/subset0/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'/content/drive/My Drive/zip/result/subset0/',
          
          #'train_annos_path':'$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',
          #'val_annos_path':'$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',
          #'test_annos_path':'$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',
         } 
